version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - temp-redis:/data
    command: redis-server
    networks:
      - redis

volumes:
  temp-redis:
    driver: local

networks:
  redis:
